site_name: CENG Wiki
site_url: https://github.com/MickeyMoos2017/Wiki
theme:
  name: material
  features:
  - content.code.copy
  - content.code.annotate
  - content.tabs.link
  custom_dir: overrides
  palette:
  - scheme: moos
  - scheme: ab
  - scheme: siemens
nav:
- Admonition: Admonition.md
- Debug safety: Debug Safety.md
- Kyaaa: KYAAA.md
- No nc: No NC.md
- Test: TEST.md
- Test1: TEST1.md
- Tesdt: Tesdt.md
- Testeir: TestEIR.md
- Testeir_2: TestEIR_2.md
- Testeir_3: TestEIR_3.md
- Code: code.md
- Def: def.md
- Index: index.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

extra_css:
- assets/styles.css
extra_javascript:
- assets/theme.js
- assets/change-title.js
markdown_extensions:
- md_in_html
- admonition
- toc
- tables
- fenced_code
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- attr_list
- pymdownx.tabbed:
    alternate_style: true
